# Dependabot configuration for Chronos Kubernetes Scheduler
# Automatically creates PRs to update dependencies

version: 2
updates:
  # Go modules dependency updates
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
    
  # Docker dependency updates for multi-stage builds
  - package-ecosystem: "docker" 
    directory: "/build"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(docker)"
      
  # GitHub Actions workflow dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"
