apiVersion: v1
kind: ServiceAccount
metadata:
  name: chronos-kubernetes-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chronos-kubernetes-scheduler
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chronos-kubernetes-scheduler
subjects:
- kind: ServiceAccount
  name: chronos-kubernetes-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: chronos-kubernetes-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chronos-kubernetes-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: chronos-kubernetes-scheduler
      plugins:
        score:
          enabled:
          - name: FastestEmptyNode
      pluginConfig:
      - name: FastestEmptyNode
    leaderElection:
      leaderElect: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronos-kubernetes-scheduler
  namespace: kube-system
  labels:
    app: chronos-kubernetes-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronos-kubernetes-scheduler
  template:
    metadata:
      labels:
        app: chronos-kubernetes-scheduler
    spec:
      serviceAccountName: chronos-kubernetes-scheduler
      containers:
      - name: scheduler
        image: chronos-kubernetes-scheduler:latest
        imagePullPolicy: IfNotPresent
        command:
        - /scheduler
        - --config=/etc/kubernetes/scheduler-config.yaml
        - --v=2
        volumeMounts:
        - name: config
          mountPath: /etc/kubernetes
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /readyz
            port: 10259
            scheme: HTTPS
      volumes:
      - name: config
        configMap:
          name: chronos-kubernetes-scheduler-config
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
