apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chronos-kubernetes-scheduler.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chronos-kubernetes-scheduler.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: {{ .Values.scheduler.name }}
      plugins:
        # Scoring plugins - hierarchical priority
        score:
          enabled:
          - name: {{ .Values.scheduler.plugin.name }}
            weight: {{ .Values.scheduler.plugin.weight | default 100 }}  # Primary: Time-based logic
          - name: NodeResourcesFit
            weight: {{ .Values.scheduler.nodeResourcesFit.weight | default 1 }}   # Secondary: Resource tie-breaking
          disabled:
          - name: "*"  # Disable all other scoring plugins for predictable behavior
        # Filter plugins - keep standard Kubernetes filters
        filter:
          enabled:
          - name: NodeResourcesFit
          - name: NodeAffinity
          - name: PodTopologySpread
          - name: TaintToleration
          - name: NodePorts
          - name: NodeVolumeLimits
          - name: VolumeBinding
      pluginConfig:
      # Chronos plugin configuration
      - name: {{ .Values.scheduler.plugin.name }}
        args:
          jobDurationAnnotation: {{ .Values.scheduler.plugin.jobDurationAnnotation | quote }}
      # NodeResourcesFit plugin configuration for sophisticated resource scoring
      - name: NodeResourcesFit
        args:
          apiVersion: kubescheduler.config.k8s.io/v1
          kind: NodeResourcesFitArgs
          scoringStrategy:
            type: {{ .Values.scheduler.nodeResourcesFit.scoringStrategy | default "MostAllocated" }}
            resources:
            - name: cpu
              weight: {{ .Values.scheduler.nodeResourcesFit.resources.cpu.weight | default 1 }}
            - name: memory  
              weight: {{ .Values.scheduler.nodeResourcesFit.resources.memory.weight | default 1 }}
    {{- if .Values.scheduler.leaderElection.enabled }}
    leaderElection:
      leaderElect: true
      leaseDuration: {{ .Values.scheduler.leaderElection.leaseDuration }}
      renewDeadline: {{ .Values.scheduler.leaderElection.renewDeadline }}
      retryPeriod: {{ .Values.scheduler.leaderElection.retryPeriod }}
      resourceName: {{ include "chronos-kubernetes-scheduler.fullname" . }}
      resourceNamespace: {{ .Release.Namespace | quote }}
    {{- else }}
    leaderElection:
      leaderElect: false
    {{- end }}
