apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chronos-kubernetes-scheduler.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chronos-kubernetes-scheduler.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    {{- if .Values.scheduler.parallelism }}
    parallelism: {{ .Values.scheduler.parallelism }}
    {{- end }}
    profiles:
    - schedulerName: {{ .Values.scheduler.name }}
      {{- $profile := index .Values.profiles .Values.scheduler.profileName }}
      {{- if not $profile }}
        {{- fail (printf "Profile '%s' not found in profiles. Available profiles: %s" .Values.scheduler.profileName (keys .Values.profiles | join ", ")) }}
      {{- end }}
      {{- if not $profile.plugins }}
        {{- fail (printf "Profile '%s' is missing required 'plugins' section" .Values.scheduler.profileName) }}
      {{- end }}
      {{- if not $profile.pluginConfig }}
        {{- fail (printf "Profile '%s' is missing required 'pluginConfig' section" .Values.scheduler.profileName) }}
      {{- end }}
      plugins:
        {{- $profile.plugins | toYaml | nindent 8 }}
      pluginConfig:
        {{- $profile.pluginConfig | toYaml | nindent 6 }}
    {{- if .Values.scheduler.leaderElection.enabled }}
    leaderElection:
      leaderElect: true
      leaseDuration: {{ .Values.scheduler.leaderElection.leaseDuration }}
      renewDeadline: {{ .Values.scheduler.leaderElection.renewDeadline }}
      retryPeriod: {{ .Values.scheduler.leaderElection.retryPeriod }}
      resourceName: {{ include "chronos-kubernetes-scheduler.fullname" . }}
      resourceNamespace: {{ .Release.Namespace | quote }}
    {{- else }}
    leaderElection:
      leaderElect: false
    {{- end }}
