apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chronos-kubernetes-scheduler.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chronos-kubernetes-scheduler.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: {{ .Values.scheduler.name }}
      plugins:
        score:
          enabled:
          - name: {{ .Values.scheduler.plugin.name }}
            weight: {{ .Values.scheduler.plugin.weight | default 100 }}
          - name: NodeResourcesFit
            weight: {{ .Values.scheduler.nodeResourcesFit.weight | default 1 }}
          disabled:
          - name: "*"
        multiPoint:
          enabled:
          - name: NodeResourcesFit
            weight: 1
      pluginConfig:
      - name: {{ .Values.scheduler.plugin.name }}
        args:
          jobDurationAnnotation: {{ .Values.scheduler.plugin.jobDurationAnnotation | quote }}
      - name: NodeResourcesFit
        args:
          apiVersion: kubescheduler.config.k8s.io/v1
          kind: NodeResourcesFitArgs
          scoringStrategy:
            type: {{ .Values.scheduler.nodeResourcesFit.scoringStrategy | default "MostAllocated" }}
            resources:
            - name: cpu
              weight: {{ .Values.scheduler.nodeResourcesFit.resources.cpu.weight | default 1 }}
            - name: memory
              weight: {{ .Values.scheduler.nodeResourcesFit.resources.memory.weight | default 1 }}
    {{- if .Values.scheduler.leaderElection.enabled }}
    leaderElection:
      leaderElect: true
      leaseDuration: {{ .Values.scheduler.leaderElection.leaseDuration }}
      renewDeadline: {{ .Values.scheduler.leaderElection.renewDeadline }}
      retryPeriod: {{ .Values.scheduler.leaderElection.retryPeriod }}
      resourceName: {{ include "chronos-kubernetes-scheduler.fullname" . }}
      resourceNamespace: {{ .Release.Namespace | quote }}
    {{- else }}
    leaderElection:
      leaderElect: false
    {{- end }}
