apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chronos-kubernetes-scheduler.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chronos-kubernetes-scheduler.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: {{ .Values.scheduler.name }}
      plugins:
        score:
          enabled:
          - name: {{ .Values.scheduler.plugin.name }}
      pluginConfig:
      - name: {{ .Values.scheduler.plugin.name }}
        args:
          jobDurationAnnotation: {{ .Values.scheduler.plugin.jobDurationAnnotation | quote }}
          scoreMultiplier: {{ .Values.scheduler.plugin.scoreMultiplier }}
    {{- if .Values.scheduler.leaderElection.enabled }}
    leaderElection:
      leaderElect: true
      leaseDuration: {{ .Values.scheduler.leaderElection.leaseDuration }}
      renewDeadline: {{ .Values.scheduler.leaderElection.renewDeadline }}
      retryPeriod: {{ .Values.scheduler.leaderElection.retryPeriod }}
      resourceName: {{ include "chronos-kubernetes-scheduler.fullname" . }}
      resourceNamespace: {{ .Release.Namespace | quote }}
    {{- else }}
    leaderElection:
      leaderElect: false
    {{- end }}
    {{- if .Values.metrics.enabled }}
    metricsBindAddress: ":{{ .Values.metrics.port }}"
    healthzBindAddress: ":{{ .Values.metrics.port }}"
    {{- else }}
    metricsBindAddress: ""
    healthzBindAddress: ""
    {{- end }}
