{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chronos-kubernetes-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chronos-kubernetes-scheduler.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "chronos-kubernetes-scheduler.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 2 }}
  {{- else }}
  ingress:
  # Allow metrics scraping
  - from: []
    ports:
    - protocol: TCP
      port: {{ .Values.metrics.port }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 2 }}
  {{- else }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow Kubernetes API access
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  # Allow webhook and extension API server access
  - to: []
    ports:
    - protocol: TCP
      port: 8443
    - protocol: TCP
      port: 9443
  {{- end }}
{{- end }}
