{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chronos-kubernetes-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chronos-kubernetes-scheduler.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chronos-kubernetes-scheduler.selectorLabels" . | nindent 6 }}
{{- end }}
