{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chronos-kubernetes-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "chronos-kubernetes-scheduler.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "chronos-kubernetes-scheduler.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    {{- with .Values.metrics.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    path: /metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
{{- end }}
