apiVersion: v2
name: chronos-kubernetes-scheduler
description: A time-aware Kubernetes scheduler that optimizes pod placement based on workload duration predictions
type: application

# Chart version - increment when making changes to the chart
version: 0.2.7

# Application version - should match the scheduler version
appVersion: "v1.0.0"

# Chart keywords for discoverability
keywords:
  - kubernetes
  - scheduler-plugin
  - optimization

# Chart homepage and sources
home: https://github.com/rohitraut3366/chronos-kubernetes-scheduler
sources:
  - https://github.com/rohitraut3366/chronos-kubernetes-scheduler

# Chart maintainers
maintainers:
  - name: Rohit Raut
    email: rohitraut3366@users.noreply.github.com

# Chart annotations for additional metadata
annotations:
  category: Infrastructure
  licenses: Apache-2.0
