name: Docker Build & Push to GHCR

on:
  push:
    branches:
      - master  # Only run on master branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Double protection - only master branch
    permissions:
      contents: read
      packages: write  # Required for GHCR push
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/chronos-kubernetes-scheduler
          tags: |
            type=raw,value={{sha}}
            type=raw,value=latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Docker Scout CVE scanning
        uses: docker/scout-action@v1
        if: github.event_name != 'pull_request'
        with:
          command: cves
          image: ghcr.io/${{ github.repository_owner }}/chronos-kubernetes-scheduler:${{ github.sha }}
          only-severities: critical,high
          only-fixed: true
