name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semver tool
        run: npm install -g semver

      - name: Calculate new version
        id: version
        run: |
          # Get current version from Chart.yaml
          CURRENT_VERSION=$(grep '^version:' charts/chronos-kubernetes-scheduler/Chart.yaml | sed 's/version: //')
          echo "Current version: $CURRENT_VERSION"
          
          # Calculate new version
          NEW_VERSION=$(semver -i ${{ github.event.inputs.bump-type }} $CURRENT_VERSION)
          echo "New version: $NEW_VERSION"
          
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update versions
        run: |
          NEW_VERSION="${{ steps.version.outputs.new }}"
          
          # Update Chart.yaml
          sed -i "s/^version:.*/version: $NEW_VERSION/" charts/chronos-kubernetes-scheduler/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"v$NEW_VERSION\"/" charts/chronos-kubernetes-scheduler/Chart.yaml
          
          # Update values.yaml
          sed -i "s/tag: .*/tag: \"v$NEW_VERSION\"/" charts/chronos-kubernetes-scheduler/values.yaml

      - name: Create version bump PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: bump version to ${{ steps.version.outputs.new }}"
          title: "🔖 Bump version to v${{ steps.version.outputs.new }}"
          body: |
            ## 🔖 Version Bump: v${{ steps.version.outputs.new }}
            
            This PR bumps the version from **v${{ steps.version.outputs.current }}** to **v${{ steps.version.outputs.new }}**.
            
            ### 📋 Changes
            - ✅ Updated Chart.yaml version: `${{ steps.version.outputs.current }}` → `${{ steps.version.outputs.new }}`
            - ✅ Updated Chart.yaml appVersion: `v${{ steps.version.outputs.current }}` → `v${{ steps.version.outputs.new }}`
            - ✅ Updated values.yaml image tag: `v${{ steps.version.outputs.current }}` → `v${{ steps.version.outputs.new }}`
            
            ### 🔄 Type
            **${{ github.event.inputs.bump-type }}** version bump
            
            ### 🚦 Next Steps
            1. **Merge** this PR
            2. Use the **Prepare Release** workflow to create an actual release
            
            ---
            
            > This PR was automatically generated by the **Bump Version** workflow.
          branch: version-bump-${{ steps.version.outputs.new }}
          delete-branch: true
          labels: |
            version-bump
            automation
